[package]
name = "hello_websocket"
version = "0.0.0"
workspace = "../../"
edition = "2018"
publish = false

[dependencies]
rocket = { path = "../../core/lib" }
futures-channel-preview = "0.3.0-alpha.19"
